Story4Fix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'


urlpatterns = [
    path('', views.about, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('skills/', views.skills, name = 'skills'),
    path('experiences/', views.experiences, name = 'experiences'),
    path('gallery/', views.gallery, name = 'gallery'),
    path('contact/', views.contact, name = 'contact'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.schedule_create, name='schedule_create'),
    path('schedule/delete', views.schedule_delete, name='schedule_delete'),
    # path('schedule/deleteone/<int:id>', views.schedule_deleteone, name='schedule_deleteone'),
    path('schedule/deletesatu/<int:id>', views.schedule_deletesatu, name='schedule_deletesatu'),
]

mainpage/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

mainpage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

mainpage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms
# Create your views here.

def about(request):
    return render(request, 'about.html')

def skills(request):    
    return render(request, 'skills2.html')

def experiences(request):
    return render(request, 'experiences.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mainpage:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})


def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

# def schedule_deleteone(request, idTemp):
#     schedule = Schedule.objects.get(id=idTemp)
#     schedule.delete()
#     return redirect('schedule')

def schedule_deletesatu(request, id):
    sched = Schedule.objects.get(id=id)
    
    sched.delete()
    return redirect('mainpage:schedule')


    

mainpage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">
    

    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 active butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

    <div id="body" class="jumbotron jumbotron-fluid text-center">
        <div class="container">
            <div class="container">
                <img src="{% static 'images/profile.jpg' %}" alt="Gafi's Photo" id="profilePicture" class="rounded-circle">
                <h1 id="nameHomePage">Mohamad Aziz Gafirazi Irfandi</h1>
                <p id="descHomePage">“Hello my name is Mohamad Aziz Gafirazi Irfandi. I am a Computer<br>Science Student at Universitas Indonesia. I was born in October 29th of<br>2000 in Jakarta. My passion is programming and coding.”</p>
            </div>

            
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    
</body>
</html>

mainpage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">
    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

    <div id="body" class="jumbotron">
        <div class="row">
            <div class="container photoSkills col-sm-6" id="textInfo">
                <p id="contact-text">CONTACT</p>
                <h1 class="headText">Get in touch</h1>
                <p class="contact-desc upper">mohamad.aziz@ui.ac.id</p>
                <p class="contact-desc">+62 8123412312</p>
                <br>
                <p class="contact-desc">Universitas Indonesia</p>
                
            </div>
        
            <div class="container photoSkills col-sm-6" id="photoslang">
                <img src="{% static 'images/profile.jpg' %}" alt="Gafi's Photo" id="foto">
            </div>
        </div>  
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

mainpage/templates/experiences.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">
    
    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

    <div id="body" class="jumbotron">
        <div class="row">
            <div class="container col-sm-6" id="textInfo">
                <h1 class="headText">Experiences:</h1>
            </div>
            <div class="container col-sm-6">
                <div class="box-exp">
                    <h1 class="headText">Education:</h1>
                    <p class="desc">2006 - 2012<span class="tab"></span>SD Cenderawasih II</p>
                    <p class="desc">2012 - 2015<span class="tab"></span>SMPN 19 Jakarta</p>
                    <p class="desc">2015 - 2018<span class="tab"></span>SMAN 70 Jakarta</p>
                    <p class="desc">2018 -<span id="tabtab"></span>Universitas Indonesia</p>
                </div>
                <div class="box-exp">
                        <h1 class="headText">Work:</h1>
                        <p class="desc">2017<span id="tabtab"></span>Staff FnB Setara</p>
                        <p class="desc">2018<span id="tabtab"></span>Staff SBF Seni Budaya</p>
                        <p class="desc">2019<span id="tabtab"></span>Mentor DDP 0</p>
                        <p class="desc">2019<span id="tabtab"></span>Assistant Lecturer DDP 1</p>
                </div>

                
            </div>
        </div>  
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

mainpage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">
    
  <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
    <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mx-auto">
            <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
            <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
            <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
            <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
            <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
            <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
        </div>
    </div> 
</nav>

    <div>
        <div class="container">
          <div class="row">
            <div class="col-sm-12 text-center">
              <br>
              <h2 class="headText text-center" id="gallery">Gallery</h2><hr>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-4">
              <a href="">
                <img src="{% static 'images/profile2.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

            <div class="col-sm-4">
              <a href="">
                <img src="{% static 'images/profile3.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

            <div class="col-sm-4">
              <a href="">
                <img src="{% static 'images/profile4.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

            <div class="col-sm-4 upper">
              <a href="">
                <img src="{% static 'images/profile5.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

            <div class="col-sm-4 upper">
              <a href="">
                <img src="{% static 'images/profile6.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

            <div class="col-sm-4 upper">
              <a href="">
                <img src="{% static 'images/profile7.jpg' %}" class="img-thumbnail">  
              </a>
            </div>

          </div>

        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    


</body>
</html>

mainpage/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">


    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

<div class="container backforms">

    <br><br><br>
    <h1 class="headText">SCHEDULE:</h1>
        <div class="article">
            <a href="{% url 'mainpage:schedule' %}"></a>
            <div class="article">
                <div class="row" id="infoText">
                    {% for schedule in schedules %}
                        <div class="col-mx-6 text-center" id="margSched">
                            <h2>{{ schedule.activity }}</h2>
                            <p>{{ schedule.date.date }}</p>
                            <p>{{ schedule.time}}</p>
                            <p>{{ schedule.place }}</p>
                            <p>{{ schedule.category }}</p>
                            <a href="{% url 'mainpage:schedule_deletesatu' id=schedule.id %}"><button type ="button" class="btn btn-danger btn-sm mt-3">Delete</button></a>
                            
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class = 'col-md-12'>
            <div class = 'form-group'>
                <a href="{% url 'mainpage:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm" id="butClear">Clear</button></a>
                <a href="{% url 'mainpage:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm" id="butCreate">Create</button></a>
            </div>
        </div>
    </div>

    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
    <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>
</html>

mainpage/templates/schedule_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">


    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

<div class="container backforms">
    <br><br><br><br><br>


    <form class="css" action="{% url 'mainpage:schedule_create' %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm-1"></div>
                <div class="form-group col-sm-10" id="infoText">
                    {% for fields in form %}
                        {{ fields.label_tag }}
                        <br>
                        {{ fields }}
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <div class="col-sm-1"></div>
                <input type="submit" class="btn btn-primary float-right" value="Add">
            </form>
    
    </div>
</div>
      
    <script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
    <script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
    <script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>

    
</body>
</html>

mainpage/templates/skills2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gafi Irfandi | Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body id="page">


    <nav class="navbar fixed-top navbar-expand-md navbar-dark my-nav" id="navbar">
        <a class="navbar-brand" href="{% url 'mainpage:about' %}" id="hrp">Mohamad Aziz Gafirazi Irfandi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mx-auto">
                <a class="nav-item nav-link mx-5 butPage" id="now" href="{% url 'mainpage:about' %}">About</a>
                <a class="nav-item nav-link mx-5 active butPage" href="{% url 'mainpage:skills' %}">Skills</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:experiences' %}">Experiences</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:gallery' %}">Gallery</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:schedule' %}">Schedule</a>
                <a class="nav-item nav-link mx-5 butPage" href="{% url 'mainpage:contact' %}">Contact</a>
            </div>
        </div> 
    </nav>

    <div id="body" class="jumbotron">
        <div class="row">
            <div class="container photoSkills col-sm-6" id="textInfo">
                <h1 class="headText">My Skills:</h1>
                <p id="descSkillsPage" class="desc">My skills are majorly in the scope of coding skills. I have mastered Python, Java, HTML, CSS. I have learned all of them from my college in Universitas Indonesia.</p>
            </div>
       
            <div class="container photoSkills col-sm-6" id="photoslang">
                <img src="{% static 'images/python.png' %}" alt="Photo of Python" id="pythonimg" class="codelang leftie upper">
                <img src="{% static 'images/java.png' %}" alt="Photo of Java" id="javaimg" class="codelang rightie upper">
                <img src="{% static 'images/html5.png' %}" alt="Photo of HTML" id="htmlimg" class="codelang leftie lower">
                <img src="{% static 'images/css.png' %}" alt="Photo of CSS" id="cssimg" class="codelang rightie lower">
            </div>
        </div>  
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>